import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { Prism } from "@mantine/prism";
import useSocket from "@hooks/useSocket";

const Home: NextPage = () => {
  const socket = useSocket();
  useEffect(() => {
    socket.on("connect", () => {
      console.log("hello World");
      socket.emit('hello')
    });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
