import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import useSocket from "@hooks/useSocket";
import { useRouter } from "next/router";
import useUserState from "@hooks/useUserState";
import Sidebar from "@components/Sidebar";
import styles from "../styles/Home.module.scss";
import { useChannelsDispatch } from "@context/Channels";
import Chat from "@components/Chat";
const Home: NextPage = () => {
  const socket = useSocket();
  const router = useRouter();
  const { username } = useUserState();
  const channelsDispatch = useChannelsDispatch();
  useEffect(() => {
    if (!username) {
      router.push("/login");
    }
    socket.emit("getChannels");
    socket.on("Channels", (channel) => {
      channelsDispatch({ type: "SET_CHANNELS", payload: channel.channels });
    });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.sidebar}>
        <Sidebar {...{ socket }} />
      </div>
      <div className={styles.chatContainer}>
        <Chat />
      </div>
    </div>
  );
};

export default Home;
